var data = [{
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 3,
    "id": 38004,
    "title": "Aperiam nesciunt qui possimus reiciendis quasi perferendis",
    "description": "Tempora perferendis ea nesciunt voluptate minima placeat eos. Eligendi similique eum. Iure vero non repellat dicta nemo quia. Quae tenetur occaecati.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-06-04T14:47:51.528Z",
    "endAt": "2021-03-13T13:02:04.426Z",
    "status": "active",
    "parentId": 37964,
    "ownerId": 10552,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "XS",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.158Z",
    "updatedAt": "2021-01-20T02:30:56.158Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38087,
    "title": "Aspernatur sit molestiae",
    "description": "Et exercitationem veniam. Nam veniam quasi exercitationem omnis enim earum error. Ut labore nobis ea vitae qui velit eum. Excepturi sed assumenda minus. Occaecati voluptatibus laudantium est quibusdam soluta optio est sint impedit. Dolores enim modi eum autem quibusdam accusamus.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2021-02-16T13:06:27.660Z",
    "endAt": "2021-02-20T16:06:09.623Z",
    "status": "active",
    "parentId": 37999,
    "ownerId": 10532,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "L",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.252Z",
    "updatedAt": "2021-01-20T02:30:56.252Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 3,
    "id": 38001,
    "title": "At occaecati pariatur ea sunt sit",
    "description": "Sed illo maiores iste ducimus. Et quod sint a debitis voluptatem molestiae quisquam non. Sequi rerum laborum dolorum modi harum odio necessitatibus quasi voluptatem. Aspernatur nemo quia. Ut molestiae voluptatibus quod earum perspiciatis. In ea ut et.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-09-25T02:05:11.407Z",
    "endAt": "2021-03-10T17:43:33.269Z",
    "status": "active",
    "parentId": 37964,
    "ownerId": 10552,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "M",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.154Z",
    "updatedAt": "2021-01-20T02:30:56.154Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 0,
    "id": 38233,
    "title": "Dolores assumenda est quos et autem",
    "description": "Tempore modi sint molestiae saepe dolores officia labore qui repudiandae. Ratione eum aut ea qui expedita dolorem. Laboriosam neque error itaque. Ut debitis rem. Ex omnis sapiente.",
    "companyId": 1076,
    "progress": 25,
    "startAt": "2020-12-20T12:57:28.020Z",
    "endAt": "2021-10-08T21:46:15.005Z",
    "status": "active",
    "parentId": 38037,
    "ownerId": 10553,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "S",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.399Z",
    "updatedAt": "2021-01-20T02:30:56.399Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38240,
    "title": "Est totam quo dolore",
    "description": "Non voluptatem molestiae. Pariatur ipsum eligendi at voluptatem explicabo quae consequatur eum distinctio. Sunt et et et et quam. Aut facere illum pariatur laudantium soluta sit laborum consequuntur.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-12-06T08:09:36.550Z",
    "endAt": "2021-05-09T07:45:46.732Z",
    "status": "active",
    "parentId": 38054,
    "ownerId": 10532,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "M",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.403Z",
    "updatedAt": "2021-01-20T02:30:56.403Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38064,
    "title": "Fugiat quo sit",
    "description": "Et inventore blanditiis qui debitis rem quia sit. Distinctio ullam labore sint. Accusamus nihil aspernatur sit ea.",
    "companyId": 1076,
    "progress": 20,
    "startAt": "2020-12-06T21:01:24.951Z",
    "endAt": "2021-10-23T03:14:12.963Z",
    "status": "active",
    "parentId": 37991,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 15,
    "weight": "S",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.238Z",
    "updatedAt": "2021-01-20T02:30:56.238Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 38035,
    "title": "Laborum repellat voluptatem voluptatem",
    "description": "Quibusdam voluptatem molestias. Aut voluptatibus alias possimus dignissimos minima id dicta. Est nobis pariatur id sequi similique aspernatur sequi quo odit. Molestias et in labore accusantium et voluptatum temporibus saepe eius.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-10-29T19:30:21.455Z",
    "endAt": "2021-10-23T12:11:44.469Z",
    "status": "active",
    "parentId": 37960,
    "ownerId": 10553,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "S",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.208Z",
    "updatedAt": "2021-01-20T02:30:56.208Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 37990,
    "title": "Minima earum alias modi necessitatibus est molestiae",
    "description": "Natus necessitatibus esse ut dolorum occaecati nemo. Aliquid qui architecto odit facilis saepe labore. Sunt rerum ea voluptas eos.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-11-18T18:49:54.164Z",
    "endAt": "2021-10-26T08:37:24.600Z",
    "status": "active",
    "parentId": 37963,
    "ownerId": 10553,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "XS",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.138Z",
    "updatedAt": "2021-01-20T02:30:56.138Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38086,
    "title": "Ratione unde totam commodi",
    "description": "Ex maxime accusamus est vel quo corrupti. Minus rerum voluptatibus dicta quibusdam et incidunt. Temporibus et qui nihil reiciendis corrupti ut ipsa quia dicta. Fuga et maxime provident vel possimus nihil voluptas harum voluptatem.",
    "companyId": 1076,
    "progress": 50,
    "startAt": "2021-01-28T17:25:40.336Z",
    "endAt": "2021-02-21T04:49:16.469Z",
    "status": "active",
    "parentId": 37999,
    "ownerId": 10532,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "M",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.251Z",
    "updatedAt": "2021-01-20T02:30:56.251Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 3,
    "id": 37962,
    "title": "Sed molestias quidem",
    "description": "Ut enim veniam quia soluta non reiciendis ducimus minima commodi. Delectus dolores qui est. Distinctio eaque quia eligendi earum vitae error dignissimos similique. Rerum aliquid totam deserunt dignissimos minus consectetur ratione ut eveniet. Rerum dolore et quidem. Ut rerum beatae quibusdam eum quidem voluptatibus.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2021-09-16T17:50:27.339Z",
    "endAt": "2021-12-15T09:21:09.163Z",
    "status": "active",
    "parentId": null,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "M",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.108Z",
    "updatedAt": "2021-01-20T02:30:56.108Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 37991,
    "title": "Soluta et libero perspiciatis aut qui error",
    "description": "Aliquid est facere dolorem. Itaque non expedita est est qui excepturi. Et enim excepturi dolorum suscipit cum at sint et. Est accusantium vel. Commodi alias consectetur error et. Architecto in omnis sint velit nulla sed fugiat et.",
    "companyId": 1076,
    "progress": 20,
    "startAt": "2021-08-23T07:56:06.038Z",
    "endAt": "2021-10-30T14:53:49.264Z",
    "status": "active",
    "parentId": 37963,
    "ownerId": 10553,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "L",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.142Z",
    "updatedAt": "2021-01-20T02:30:56.142Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 0,
    "id": 38099,
    "title": "Ut dolorum atque ut",
    "description": "Rerum in molestiae mollitia quod illum totam. Ipsa fugiat in exercitationem dignissimos quam facere reprehenderit assumenda consequatur. Ea saepe sint nemo. Magni assumenda architecto quas quod id debitis nihil. Voluptas ut et similique sunt aut ut non. Eaque rerum fugit dolores totam maxime adipisci.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-12-15T20:37:56.113Z",
    "endAt": "2021-03-09T23:49:02.204Z",
    "status": "active",
    "parentId": 38003,
    "ownerId": 10552,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XS",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.264Z",
    "updatedAt": "2021-01-20T02:30:56.264Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38219,
    "title": "Ut similique laboriosam dolor quis qui",
    "description": "Quas iste magni veniam ex facilis. Laborum aperiam nihil dolor quidem vero maxime quia voluptatum non. Et fugiat et voluptates vero quibusdam autem laborum alias. Autem et atque magnam ipsam harum voluptas eum perferendis sed. Alias qui et magnam nisi aperiam omnis atque.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-09-28T22:51:10.185Z",
    "endAt": "2021-12-06T04:09:51.835Z",
    "status": "active",
    "parentId": 38032,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "S",
    "priority": -30,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.394Z",
    "updatedAt": "2021-01-20T02:30:56.394Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38091,
    "title": "A praesentium qui sit in deserunt",
    "description": "Enim architecto doloribus enim consectetur eius reprehenderit consequatur. Consectetur natus numquam. Consequatur soluta rerum pariatur sed omnis.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-01-10T09:57:57.531Z",
    "endAt": "2021-02-10T05:56:54.382Z",
    "status": "active",
    "parentId": 38000,
    "ownerId": 10532,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "L",
    "priority": -20,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.256Z",
    "updatedAt": "2021-01-20T02:30:56.256Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10549,
        "avatar": null,
        "firstName": "Haven",
        "lastName": "Anderson",
        "displayName": "Haven Anderson"
    },
    "subGoalCounts": 3,
    "id": 38054,
    "title": "At saepe quam",
    "description": "Sed minima et omnis fuga quo voluptas. Dolore sed esse voluptate. Libero voluptatem sit velit dolor et non et. Dignissimos sit cum sit accusamus numquam suscipit esse laborum inventore.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-12-19T23:48:33.380Z",
    "endAt": "2021-05-11T22:31:52.845Z",
    "status": "active",
    "parentId": 37965,
    "ownerId": 10549,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "XS",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.232Z",
    "updatedAt": "2021-01-20T02:30:56.232Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38224,
    "title": "Autem molestias et nam facilis rerum atque",
    "description": "Voluptatibus est veritatis ex sequi. Aut et ab adipisci eum. Eos est ut dignissimos illum dicta cumque. Et doloribus consequatur iure autem distinctio qui aut. Id sed sequi non. Et modi ab vitae maxime.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-10-19T21:35:23.776Z",
    "endAt": "2021-10-13T14:05:50.915Z",
    "status": "active",
    "parentId": 38035,
    "ownerId": 10532,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": -20,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.397Z",
    "updatedAt": "2021-01-20T02:30:56.397Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10549,
        "avatar": null,
        "firstName": "Haven",
        "lastName": "Anderson",
        "displayName": "Haven Anderson"
    },
    "subGoalCounts": 0,
    "id": 38244,
    "title": "Consectetur doloribus aut minus saepe",
    "description": "Dolores quae qui quaerat veritatis aliquam. Delectus et voluptatem temporibus omnis facere quis est. Autem asperiores et ut qui. Ut exercitationem soluta exercitationem porro veritatis eveniet optio animi omnis. Voluptate soluta recusandae omnis.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-11-16T08:00:21.980Z",
    "endAt": "2021-05-09T18:29:12.260Z",
    "status": "active",
    "parentId": 38055,
    "ownerId": 10549,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "L",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.404Z",
    "updatedAt": "2021-01-20T02:30:56.404Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 3,
    "id": 37965,
    "title": "Dolor recusandae est",
    "description": "Consectetur quasi omnis sunt qui. Modi earum eum id maiores aut. Dolore rerum sint repellendus. Ea sunt saepe quasi maiores placeat fuga nulla perspiciatis vel.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-09-17T22:47:51.203Z",
    "endAt": "2021-05-19T16:36:28.377Z",
    "status": "active",
    "parentId": null,
    "ownerId": 10532,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "S",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.108Z",
    "updatedAt": "2021-01-20T02:30:56.108Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38241,
    "title": "Dolor tenetur qui",
    "description": "Qui in impedit eos aut commodi. Ex quisquam voluptate deleniti provident aut iure in quaerat iusto. Omnis ex ab sequi dolore eveniet expedita aut. Sequi beatae perspiciatis sed architecto. Ducimus mollitia architecto enim.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-11-26T07:31:45.383Z",
    "endAt": "2021-05-05T22:46:09.540Z",
    "status": "active",
    "parentId": 38054,
    "ownerId": 10532,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "XS",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.404Z",
    "updatedAt": "2021-01-20T02:30:56.404Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 0,
    "id": 38097,
    "title": "Dolorum excepturi occaecati porro aut",
    "description": "Repudiandae et quibusdam amet expedita delectus et ut beatae soluta. Consectetur soluta mollitia. Mollitia quia qui voluptates quae nobis. Qui ex aut assumenda nisi.",
    "companyId": 1076,
    "progress": 15,
    "startAt": "2020-06-24T11:18:21.364Z",
    "endAt": "2021-03-03T07:25:31.260Z",
    "status": "active",
    "parentId": 38002,
    "ownerId": 10552,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.260Z",
    "updatedAt": "2021-01-20T02:30:56.260Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 3,
    "id": 38003,
    "title": "Explicabo dolor repellendus qui",
    "description": "Non ab quae aut earum ipsa aut modi quia officia. Beatae mollitia minus quo voluptas officiis. Cumque aspernatur pariatur et quaerat dolor quasi rerum officia dicta. Aliquam magnam ab autem.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-07-29T06:59:19.916Z",
    "endAt": "2021-03-15T18:14:08.228Z",
    "status": "active",
    "parentId": 37964,
    "ownerId": 10552,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "XL",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.158Z",
    "updatedAt": "2021-01-20T02:30:56.158Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 3,
    "id": 37960,
    "title": "Nostrum aperiam aut quisquam tempore",
    "description": "Veniam eligendi dolor cumque ex qui eos. Tempora quidem est molestiae sed magni. Et atque velit. Consequatur qui consequuntur numquam. Vel eos soluta voluptas veniam est tempora voluptates quis.",
    "companyId": 1076,
    "progress": 30,
    "startAt": "2020-12-14T13:25:57.577Z",
    "endAt": "2021-11-02T08:34:45.254Z",
    "status": "active",
    "parentId": null,
    "ownerId": 10532,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "M",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.107Z",
    "updatedAt": "2021-01-20T02:30:56.107Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38227,
    "title": "Omnis accusamus tempora soluta autem",
    "description": "Veniam quaerat molestias id rerum. Distinctio ut et dolorem provident quae corporis dolor molestiae. Est modi vitae ut quia quidem ut impedit amet. Minima ipsa eum praesentium deleniti consequatur occaecati. Molestias sed est quae aliquid.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-08-21T04:10:56.628Z",
    "endAt": "2021-12-09T03:37:57.519Z",
    "status": "active",
    "parentId": 38034,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "S",
    "priority": -20,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.398Z",
    "updatedAt": "2021-01-20T02:30:56.398Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 0,
    "id": 38230,
    "title": "Quasi voluptas inventore voluptatem temporibus eum",
    "description": "Aliquid facere iste cumque omnis quo. Iusto rerum et recusandae porro pariatur itaque ad. Alias id sed. Veritatis reprehenderit aliquam id aspernatur.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2021-09-29T06:26:51.265Z",
    "endAt": "2021-10-17T10:03:48.821Z",
    "status": "active",
    "parentId": 38036,
    "ownerId": 10553,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "S",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.399Z",
    "updatedAt": "2021-01-20T02:30:56.399Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 3,
    "id": 38002,
    "title": "Quis voluptatem magnam sed",
    "description": "Aut impedit est. Inventore consequatur hic. Exercitationem itaque aut accusamus sint est inventore perferendis neque.",
    "companyId": 1076,
    "progress": 15,
    "startAt": "2020-05-28T01:42:04.550Z",
    "endAt": "2021-03-07T09:17:46.559Z",
    "status": "active",
    "parentId": 37961,
    "ownerId": 10552,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "M",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.154Z",
    "updatedAt": "2021-01-20T02:30:56.154Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38234,
    "title": "Ratione in nemo quia",
    "description": "Sunt autem architecto quae officiis vitae laborum qui placeat. Quidem sit amet deserunt atque. Excepturi excepturi dicta quia maiores ut voluptas ad est sapiente. Eum modi ipsum. Assumenda esse sit consequuntur nesciunt.",
    "companyId": 1076,
    "progress": 15,
    "startAt": "2021-01-13T07:32:47.185Z",
    "endAt": "2021-10-07T01:10:20.489Z",
    "status": "active",
    "parentId": 38037,
    "ownerId": 10532,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "L",
    "priority": -20,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.400Z",
    "updatedAt": "2021-01-20T02:30:56.400Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38105,
    "title": "Ut cupiditate natus expedita neque eum",
    "description": "Laudantium quis doloremque minima. Deserunt et autem iusto. Adipisci veritatis laboriosam omnis non.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-04-23T05:43:59.295Z",
    "endAt": "2021-03-04T18:06:41.104Z",
    "status": "active",
    "parentId": 38004,
    "ownerId": 10532,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "L",
    "priority": -20,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.268Z",
    "updatedAt": "2021-01-20T02:30:56.268Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 38032,
    "title": "Voluptate rerum ut earum dignissimos ipsa",
    "description": "Voluptate veritatis nam culpa deleniti consectetur ea. Fuga qui fugit. Ut quis corrupti voluptas enim qui id porro sit.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-12-21T03:09:45.333Z",
    "endAt": "2021-12-14T01:11:03.652Z",
    "status": "active",
    "parentId": 37962,
    "ownerId": 10553,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "XS",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.207Z",
    "updatedAt": "2021-01-20T02:30:56.207Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 38034,
    "title": "Voluptates eveniet et",
    "description": "Consequatur et et cumque ab. Maxime doloribus sed tempore soluta at qui consequuntur rerum. Sed sunt et ad hic itaque eligendi cumque esse. Sunt quidem assumenda. Qui deserunt aut aut pariatur quisquam ratione nihil.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-12-29T15:17:34.659Z",
    "endAt": "2021-12-11T17:05:36.278Z",
    "status": "active",
    "parentId": 37962,
    "ownerId": 10553,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "XL",
    "priority": -20,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.208Z",
    "updatedAt": "2021-01-20T02:30:56.208Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38222,
    "title": "Architecto quae qui numquam",
    "description": "Consequatur quisquam at perferendis facere. Sequi aliquam dolores alias aliquam est autem corrupti. Autem consequatur consequatur possimus molestias consectetur odit sint. Illum et iusto voluptatem dolorem architecto quod nemo aliquid.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-06-20T23:23:39.796Z",
    "endAt": "2021-12-07T05:43:07.759Z",
    "status": "active",
    "parentId": 38033,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "XS",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.397Z",
    "updatedAt": "2021-01-20T02:30:56.397Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38228,
    "title": "Aspernatur quis maiores officia",
    "description": "Nihil ea nam accusantium eveniet. Occaecati eaque temporibus error. Tenetur et nam ea culpa consequatur dolor.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-07-12T10:34:12.081Z",
    "endAt": "2021-12-01T05:16:17.143Z",
    "status": "active",
    "parentId": 38034,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "M",
    "priority": -10,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.398Z",
    "updatedAt": "2021-01-20T02:30:56.398Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 0,
    "id": 38061,
    "title": "Atque consectetur iusto quam nisi molestiae",
    "description": "Sint tempora blanditiis aperiam quia. Quasi fugiat earum. Et sed eos. Sint ipsa veniam soluta eius omnis et reprehenderit.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-06-04T12:38:21.109Z",
    "endAt": "2021-10-19T16:00:59.615Z",
    "status": "active",
    "parentId": 37990,
    "ownerId": 10553,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "S",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.237Z",
    "updatedAt": "2021-01-20T02:30:56.237Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38231,
    "title": "Aut et expedita repudiandae sint",
    "description": "Sunt sed qui. Eius animi labore qui ducimus numquam consequatur. Doloribus tempore laboriosam molestiae voluptatem et. Aut est illum aspernatur quam natus alias aut pariatur quis. Voluptatem optio corporis quia nihil dicta optio eos deleniti eos. Sit eligendi mollitia odit.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2021-08-15T19:10:00.679Z",
    "endAt": "2021-10-18T01:38:20.865Z",
    "status": "active",
    "parentId": 38036,
    "ownerId": 10532,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "M",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.399Z",
    "updatedAt": "2021-01-20T02:30:56.399Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 0,
    "id": 38067,
    "title": "Eos expedita dolorum praesentium quas iste enim",
    "description": "Excepturi dolore maxime voluptates quas quia. Sed voluptatibus est voluptatem. Harum sunt id est. Nostrum delectus ea deleniti necessitatibus molestias quisquam recusandae quia impedit.",
    "companyId": 1076,
    "progress": 20,
    "startAt": "2021-10-22T09:50:40.867Z",
    "endAt": "2021-10-23T16:48:43.988Z",
    "status": "active",
    "parentId": 37992,
    "ownerId": 10553,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "M",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.241Z",
    "updatedAt": "2021-01-20T02:30:56.241Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38098,
    "title": "Est molestiae aut",
    "description": "Porro ducimus eum corporis. Earum et maiores et laborum vitae non est voluptate. Dolorum veniam id culpa laboriosam natus totam aut rerum. Asperiores culpa est nemo et ea. Quasi numquam laborum pariatur illum.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-10-09T21:28:08.911Z",
    "endAt": "2021-03-11T10:56:26.549Z",
    "status": "active",
    "parentId": 38003,
    "ownerId": 10532,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "XL",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.261Z",
    "updatedAt": "2021-01-20T02:30:56.261Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10549,
        "avatar": null,
        "firstName": "Haven",
        "lastName": "Anderson",
        "displayName": "Haven Anderson"
    },
    "subGoalCounts": 0,
    "id": 38237,
    "title": "Quo vitae aut recusandae laboriosam ea adipisci",
    "description": "Amet eos ducimus minus voluptas deleniti. Doloribus sapiente blanditiis excepturi sed. Consectetur et culpa accusamus cum.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-07-14T07:53:35.089Z",
    "endAt": "2021-05-05T23:46:55.343Z",
    "status": "active",
    "parentId": 38053,
    "ownerId": 10549,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "S",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.401Z",
    "updatedAt": "2021-01-20T02:30:56.401Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38062,
    "title": "Ut hic enim",
    "description": "Omnis accusantium dolorem quam tempore fugit. Et qui esse. Quaerat sit ut voluptas consequatur dolores fugit necessitatibus dolorem. Deserunt iure id odit consequuntur ipsam quidem laborum.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-11-10T17:15:22.916Z",
    "endAt": "2021-10-24T20:39:34.743Z",
    "status": "active",
    "parentId": 37991,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "S",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.237Z",
    "updatedAt": "2021-01-20T02:30:56.237Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 37992,
    "title": "Vel quasi vel adipisci fugiat est accusamus",
    "description": "Et laboriosam repudiandae. Pariatur sed minima ipsa temporibus voluptatem sed repellat. Officiis voluptas voluptas doloribus fugit quia ab. Ut repudiandae et.",
    "companyId": 1076,
    "progress": 40,
    "startAt": "2021-08-10T10:57:13.338Z",
    "endAt": "2021-10-29T23:50:08.026Z",
    "status": "active",
    "parentId": 37963,
    "ownerId": 10553,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "L",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.142Z",
    "updatedAt": "2021-01-20T02:30:56.142Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 0,
    "id": 38104,
    "title": "Velit tempora laborum ratione ut qui voluptates",
    "description": "Libero possimus optio ut. Quo qui ut exercitationem dolorem saepe deleniti quia eius aperiam. Excepturi quia et ut. Aut quia molestias reprehenderit architecto. Et quia iure numquam magni quam repellendus ea maiores atque. Quae dolorem est perferendis sit.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-11-07T18:57:16.996Z",
    "endAt": "2021-03-02T16:16:35.291Z",
    "status": "active",
    "parentId": 38004,
    "ownerId": 10552,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "S",
    "priority": -10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.267Z",
    "updatedAt": "2021-01-20T02:30:56.267Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38225,
    "title": "Voluptatum sed voluptatum et blanditiis est",
    "description": "Qui in recusandae laborum qui omnis sit. Occaecati laboriosam consequatur necessitatibus molestiae. Cupiditate officia commodi eum reprehenderit eligendi qui velit. Nulla delectus cum fuga et.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2021-08-17T04:34:54.029Z",
    "endAt": "2021-10-17T06:56:13.053Z",
    "status": "active",
    "parentId": 38035,
    "ownerId": 10532,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "M",
    "priority": -10,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.397Z",
    "updatedAt": "2021-01-20T02:30:56.397Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38060,
    "title": "Alias amet quod excepturi et impedit",
    "description": "Omnis expedita ipsam dolorem est est consequatur. Eum eum quia ut. Optio a consequuntur numquam dignissimos et labore est.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-12-19T01:44:54.819Z",
    "endAt": "2021-10-26T03:04:37.492Z",
    "status": "active",
    "parentId": 37990,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "XL",
    "priority": 0,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.237Z",
    "updatedAt": "2021-01-20T02:30:56.237Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38088,
    "title": "Amet praesentium recusandae nesciunt aliquid ducimus",
    "description": "Culpa asperiores cum. Et impedit voluptatum ut maxime dolor est qui provident commodi. Dolore aut nesciunt repellendus ut vel ipsa est magni. Harum optio dolores fugiat aspernatur aut unde et. Quas aut dolorem.",
    "companyId": 1076,
    "progress": 35,
    "startAt": "2020-12-26T21:51:18.166Z",
    "endAt": "2021-02-22T10:33:13.711Z",
    "status": "active",
    "parentId": 37999,
    "ownerId": 10532,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": -10,
    "weight": "XS",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.252Z",
    "updatedAt": "2021-01-20T02:30:56.252Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38220,
    "title": "Animi quia nihil optio aliquam nihil vel",
    "description": "Nesciunt labore dignissimos ut enim autem. Et blanditiis autem autem et consequuntur autem. Cupiditate voluptatem eveniet. Quae delectus at.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-02-12T09:15:24.290Z",
    "endAt": "2021-12-06T22:26:58.868Z",
    "status": "active",
    "parentId": 38032,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "XS",
    "priority": 0,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.394Z",
    "updatedAt": "2021-01-20T02:30:56.394Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38100,
    "title": "Eligendi sit error mollitia sit blanditiis",
    "description": "Incidunt excepturi voluptas ad tenetur. Cum sit explicabo aspernatur quibusdam aspernatur sed. Ducimus sequi quia saepe quisquam placeat et. Impedit rerum facere ea corporis omnis. Incidunt fuga ex ut eius enim et consequatur eius aut.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-10-11T22:16:47.585Z",
    "endAt": "2021-03-08T01:37:11.728Z",
    "status": "active",
    "parentId": 38003,
    "ownerId": 10532,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "M",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.265Z",
    "updatedAt": "2021-01-20T02:30:56.265Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 0,
    "id": 38229,
    "title": "In sint tenetur voluptatem",
    "description": "Est cum optio dolorem sint. Qui animi incidunt. Rem dolorum assumenda et reprehenderit labore iure omnis facilis corporis.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2021-11-23T00:02:07.230Z",
    "endAt": "2021-12-04T07:12:47.090Z",
    "status": "active",
    "parentId": 38034,
    "ownerId": 10553,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "XL",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.399Z",
    "updatedAt": "2021-01-20T02:30:56.399Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38243,
    "title": "Omnis at dolores dicta rerum quidem corrupti",
    "description": "Libero debitis maxime omnis itaque ut voluptate. Corporis odit tempore consequatur. Sint enim porro ut deserunt et est tempora. Alias similique alias cumque. Aperiam et facere.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-01-19T03:24:39.393Z",
    "endAt": "2021-05-10T12:58:31.563Z",
    "status": "active",
    "parentId": 38055,
    "ownerId": 10532,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "L",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.404Z",
    "updatedAt": "2021-01-20T02:30:56.404Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38238,
    "title": "Quae beatae voluptatem dolorum iusto est",
    "description": "Eaque a sapiente quos eius blanditiis quam dolores nulla natus. Consequuntur blanditiis quia dolor facere earum. Et et et aperiam porro architecto atque. Animi amet a laboriosam repudiandae. Deserunt quia qui reprehenderit laudantium necessitatibus dolorem nisi veniam. Delectus quae reprehenderit.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-11-06T21:34:45.564Z",
    "endAt": "2021-05-13T14:27:35.092Z",
    "status": "active",
    "parentId": 38053,
    "ownerId": 10532,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "S",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.403Z",
    "updatedAt": "2021-01-20T02:30:56.403Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38066,
    "title": "Quibusdam ut non numquam quod eius",
    "description": "Nihil recusandae commodi numquam quisquam sed. Perferendis iure ut. Unde nobis laboriosam ea consequatur.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2021-01-19T05:10:32.049Z",
    "endAt": "2021-10-21T19:21:47.539Z",
    "status": "active",
    "parentId": 37992,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "S",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.239Z",
    "updatedAt": "2021-01-20T02:30:56.239Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38059,
    "title": "Quidem sint error ut aspernatur",
    "description": "Temporibus odit vel neque. Enim corporis eius velit. Et sit nihil nulla. Corporis sed ad ut ut et illo sunt quae.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2021-05-05T12:45:31.579Z",
    "endAt": "2021-10-16T08:05:28.600Z",
    "status": "active",
    "parentId": 37990,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "XL",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.234Z",
    "updatedAt": "2021-01-20T02:30:56.234Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10549,
        "avatar": null,
        "firstName": "Haven",
        "lastName": "Anderson",
        "displayName": "Haven Anderson"
    },
    "subGoalCounts": 3,
    "id": 38053,
    "title": "Totam itaque accusantium reprehenderit doloremque",
    "description": "Est cum et. Fuga iste qui veritatis voluptatum. Corporis corporis sunt quia corrupti illum harum. Aut in necessitatibus delectus velit nostrum in consequatur. Voluptatibus fuga dolorem nostrum accusantium vel hic.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-12-09T08:33:50.937Z",
    "endAt": "2021-05-19T13:01:15.152Z",
    "status": "active",
    "parentId": 37965,
    "ownerId": 10549,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XS",
    "priority": 0,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.230Z",
    "updatedAt": "2021-01-20T02:30:56.230Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38065,
    "title": "Assumenda itaque voluptate veritatis",
    "description": "Voluptates minima id neque est quia. Harum explicabo voluptatem. Sapiente sed qui et sed qui id velit dolores.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-08-05T16:39:57.721Z",
    "endAt": "2021-10-17T01:35:33.915Z",
    "status": "active",
    "parentId": 37992,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "S",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.238Z",
    "updatedAt": "2021-01-20T02:30:56.238Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 38036,
    "title": "Consequatur id eum sed dolores incidunt",
    "description": "Laboriosam enim et nemo. Sint sunt culpa nostrum blanditiis. Cupiditate at voluptatem non recusandae nihil doloribus cum molestias.",
    "companyId": 1076,
    "progress": 15,
    "startAt": "2021-06-23T13:23:08.842Z",
    "endAt": "2021-10-23T18:58:01.774Z",
    "status": "active",
    "parentId": 37960,
    "ownerId": 10553,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": 15,
    "weight": "L",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.209Z",
    "updatedAt": "2021-01-20T02:30:56.209Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 3,
    "id": 37961,
    "title": "Corrupti consequatur vitae iure eum consequatur",
    "description": "Nihil rerum exercitationem voluptatem odit sint cupiditate. Neque tempora necessitatibus vero maxime deleniti. Odit nam dicta delectus quas saepe error et nam dolor. Animi asperiores minima.",
    "companyId": 1076,
    "progress": 80,
    "startAt": "2020-11-29T00:50:19.521Z",
    "endAt": "2021-03-09T04:28:13.624Z",
    "status": "active",
    "parentId": null,
    "ownerId": 10532,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 10,
    "weight": "M",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.107Z",
    "updatedAt": "2021-01-20T02:30:56.107Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 38033,
    "title": "Delectus dolore est expedita rerum consequatur delectus",
    "description": "Asperiores blanditiis est ea. Adipisci numquam dolorem est qui quos corrupti voluptas et. Dicta quis quibusdam perferendis magni ea ab quis in. Perferendis quia ut neque doloribus.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-03-29T20:28:26.877Z",
    "endAt": "2021-12-13T10:16:07.830Z",
    "status": "active",
    "parentId": 37962,
    "ownerId": 10553,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.207Z",
    "updatedAt": "2021-01-20T02:30:56.207Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 3,
    "id": 37963,
    "title": "Dolores odio voluptatem dolor possimus",
    "description": "Autem officia ipsum rerum eum. Tempora aut minus harum neque minus quas. Enim velit quas architecto explicabo deserunt. Culpa fugiat voluptate quo ut cumque aut earum.",
    "companyId": 1076,
    "progress": 80,
    "startAt": "2021-07-23T16:37:33.317Z",
    "endAt": "2021-10-31T10:52:51.048Z",
    "status": "active",
    "parentId": null,
    "ownerId": 10532,
    "goalColor": "#f798d4",
    "tag": "Doloribus",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.108Z",
    "updatedAt": "2021-01-20T02:30:56.108Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38218,
    "title": "Et magni omnis rerum",
    "description": "Sit id cumque facilis ut. Voluptas qui temporibus et tenetur molestias. Accusamus totam voluptates qui inventore et vel atque expedita.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-12-15T19:05:48.515Z",
    "endAt": "2021-12-06T01:23:19.678Z",
    "status": "active",
    "parentId": 38032,
    "ownerId": 10532,
    "goalColor": "#8fe359",
    "tag": "Architecto e",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.394Z",
    "updatedAt": "2021-01-20T02:30:56.394Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38094,
    "title": "Facilis enim maiores debitis",
    "description": "Dolore eveniet minus ut. Aliquid veritatis perspiciatis totam facere asperiores. Fugiat pariatur aut eos ut omnis aut distinctio.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2020-03-22T18:31:17.292Z",
    "endAt": "2021-02-28T12:22:15.174Z",
    "status": "active",
    "parentId": 38001,
    "ownerId": 10532,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.258Z",
    "updatedAt": "2021-01-20T02:30:56.258Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38106,
    "title": "Fuga quod deserunt ea nostrum et",
    "description": "Eos assumenda nihil id. Sint autem asperiores velit. Quia pariatur laborum vel. Recusandae aut quas magni temporibus aliquam incidunt mollitia nam. Recusandae qui aliquam quibusdam explicabo eos itaque sunt. Tempora accusamus molestiae dolor necessitatibus beatae doloribus.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-10-16T05:37:01.904Z",
    "endAt": "2021-03-02T07:41:30.831Z",
    "status": "active",
    "parentId": 38004,
    "ownerId": 10532,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "L",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.269Z",
    "updatedAt": "2021-01-20T02:30:56.269Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 3,
    "id": 37964,
    "title": "Laborum pariatur qui",
    "description": "Voluptatem ducimus enim saepe dolor. Aliquid incidunt culpa. Ipsam harum omnis animi iusto labore error. Unde ut culpa ab assumenda ea molestiae qui possimus id.",
    "companyId": 1076,
    "progress": 10,
    "startAt": "2021-01-21T13:52:00.954Z",
    "endAt": "2021-03-22T11:49:38.148Z",
    "status": "active",
    "parentId": null,
    "ownerId": 10532,
    "goalColor": "#40c29e",
    "tag": "Non",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XS",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.108Z",
    "updatedAt": "2021-01-20T02:30:56.108Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 3,
    "id": 38037,
    "title": "Magni est dolor",
    "description": "Id voluptatem quod neque odit nulla omnis aut quia. Voluptas aut voluptatem ut ullam possimus sit consequatur doloribus. Eos atque mollitia temporibus quo quod maiores fugit. Consequuntur atque est sed aut nobis magnam quo. Id ea sequi nemo.",
    "companyId": 1076,
    "progress": 30,
    "startAt": "2021-03-30T15:03:50.263Z",
    "endAt": "2021-10-20T06:39:06.696Z",
    "status": "active",
    "parentId": 37960,
    "ownerId": 10553,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": 10,
    "weight": "M",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.210Z",
    "updatedAt": "2021-01-20T02:30:56.210Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10553,
        "avatar": null,
        "firstName": "Hayley",
        "lastName": "Beer",
        "displayName": "Hayley Beer"
    },
    "subGoalCounts": 0,
    "id": 38226,
    "title": "Non labore sunt eius laudantium ipsum",
    "description": "In sed ipsa vero non harum reprehenderit dolor in. Inventore et quidem nemo ea at. Alias ratione quas voluptatem voluptas. Eum labore dolorum voluptatem qui culpa vel nesciunt eligendi est. Odio sed blanditiis. Ducimus ipsa est sit laudantium omnis.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2021-02-20T17:37:20.511Z",
    "endAt": "2021-10-22T22:11:14.928Z",
    "status": "active",
    "parentId": 38035,
    "ownerId": 10553,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -15,
    "weight": "XS",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.398Z",
    "updatedAt": "2021-01-20T02:30:56.398Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 0,
    "id": 38096,
    "title": "Odio atque est sunt id cumque",
    "description": "Autem soluta quia in voluptas qui nobis et labore et. Itaque ea error suscipit debitis. Tempore minus fugit soluta quibusdam hic. Aut dolorum qui sed occaecati.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-04-26T22:51:02.409Z",
    "endAt": "2021-03-01T10:18:56.665Z",
    "status": "active",
    "parentId": 38002,
    "ownerId": 10552,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XL",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.258Z",
    "updatedAt": "2021-01-20T02:30:56.258Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 3,
    "id": 37999,
    "title": "Pariatur fugit dolorum eos",
    "description": "Consequatur possimus et. Aspernatur doloremque dolor deserunt ut sint. Officia quo dolores recusandae deleniti. Facilis vitae facere quis qui sit recusandae eius.",
    "companyId": 1076,
    "progress": 75,
    "startAt": "2020-06-23T07:34:04.922Z",
    "endAt": "2021-03-03T00:48:42.121Z",
    "status": "active",
    "parentId": 37961,
    "ownerId": 10552,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 25,
    "weight": "S",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.153Z",
    "updatedAt": "2021-01-20T02:30:56.153Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38235,
    "title": "Provident perferendis nulla corporis alias quisquam incidunt",
    "description": "Atque laboriosam suscipit facere minima ut veniam. Laboriosam sint sequi voluptatem deserunt nihil nulla occaecati. Dolorem quidem cupiditate consectetur rerum culpa et non beatae. Et ratione qui voluptatibus assumenda et. Unde ut repudiandae aliquid expedita sint odio non.",
    "companyId": 1076,
    "progress": 25,
    "startAt": "2021-05-19T10:37:09.200Z",
    "endAt": "2021-10-19T01:09:21.171Z",
    "status": "active",
    "parentId": 38037,
    "ownerId": 10532,
    "goalColor": "#a8e0c0",
    "tag": "Et cupiditat",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "M",
    "priority": 10,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.401Z",
    "updatedAt": "2021-01-20T02:30:56.401Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1108],
    "teams": [{
        "teamId": 1108,
        "name": "Toys",
        "color": "#6a291f",
        "teamOwnerId": 10532
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10552,
        "avatar": null,
        "firstName": "Edmund",
        "lastName": "Mertz",
        "displayName": "Edmund Mertz"
    },
    "subGoalCounts": 3,
    "id": 38000,
    "title": "Quos sapiente cumque nostrum fugit aut et",
    "description": "Est sit sed facilis fugit et aut nemo atque. Cum cum sed autem. Consequatur impedit numquam est. Nobis quia quo nihil. Omnis doloribus illo unde velit quas totam quas quia.",
    "companyId": 1076,
    "progress": 5,
    "startAt": "2020-08-09T18:23:07.364Z",
    "endAt": "2021-02-24T03:58:52.354Z",
    "status": "active",
    "parentId": 37961,
    "ownerId": 10552,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": 5,
    "weight": "M",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.153Z",
    "updatedAt": "2021-01-20T02:30:56.153Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38095,
    "title": "Sint dolorem et corrupti autem est",
    "description": "Ex qui culpa nisi sunt. Explicabo quae corrupti natus beatae ea et perferendis blanditiis ut. Minus et natus sunt earum occaecati. Voluptatem repellat animi et iure beatae cupiditate ut.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2020-03-24T13:07:10.784Z",
    "endAt": "2021-03-02T15:40:56.567Z",
    "status": "active",
    "parentId": 38002,
    "ownerId": 10532,
    "goalColor": "#7cbc8b",
    "tag": "Dolore",
    "dueDateEnabled": true,
    "progressDelta": -5,
    "weight": "S",
    "priority": 10,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.258Z",
    "updatedAt": "2021-01-20T02:30:56.258Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [],
    "teams": []
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10549,
        "avatar": null,
        "firstName": "Haven",
        "lastName": "Anderson",
        "displayName": "Haven Anderson"
    },
    "subGoalCounts": 3,
    "id": 38055,
    "title": "Velit quo autem illo sed",
    "description": "Odit sed nesciunt distinctio nam magnam rerum aut. Non ad autem tenetur a numquam voluptate. Id eos voluptas perspiciatis rerum sunt non. Commodi quam quaerat.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-04-26T16:59:11.188Z",
    "endAt": "2021-05-13T22:01:22.512Z",
    "status": "active",
    "parentId": 37965,
    "ownerId": 10549,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "XS",
    "priority": 10,
    "isPrivate": false,
    "createdAt": "2021-01-20T02:30:56.232Z",
    "updatedAt": "2021-01-20T02:30:56.232Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}, {
    "numOfAttachments": 0,
    "owner": {
        "id": 10532,
        "avatar": null,
        "firstName": "Alex",
        "lastName": "Peterson",
        "displayName": "Alex Peterson"
    },
    "subGoalCounts": 0,
    "id": 38242,
    "title": "Vitae nesciunt sit quas est autem",
    "description": "Eum et explicabo qui rerum voluptas ducimus libero. Esse maxime sequi ea corrupti voluptatem autem nostrum. Officia sint ipsum soluta sint magnam earum.",
    "companyId": 1076,
    "progress": 0,
    "startAt": "2021-03-22T14:24:30.373Z",
    "endAt": "2021-05-10T07:12:36.368Z",
    "status": "active",
    "parentId": 38055,
    "ownerId": 10532,
    "goalColor": "#bb7e5c",
    "tag": "Est quos",
    "dueDateEnabled": true,
    "progressDelta": 0,
    "weight": "L",
    "priority": 10,
    "isPrivate": true,
    "createdAt": "2021-01-20T02:30:56.404Z",
    "updatedAt": "2021-01-20T02:30:56.404Z",
    "completedAt": null,
    "showAsCompanyGoal": true,
    "teamIds": [1109],
    "teams": [{
        "teamId": 1109,
        "name": "Computers",
        "color": "#2b2232",
        "teamOwnerId": 10547
    }]
}]

var callback = function(node) {
    document.getElementById("callback_label").innerHTML =
        "startAt : " + node.startAt +
        ", endtAt : " + node.endAt
        //  +
        // ", left : " + node.left +
        // ", right : " + node.right +
        // ", parent : " + node.parentId;
}

var config = {
    data: data, // Your actuall data
    callback: callback, // callback function
    element: "#Chart", // The element for rendering the chart
}

goalChart(config);